name: CI and tests

on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Melon
        run: yarn

      - name: Check license
        run: yarn licenseCheck
